### ISSUE TITLE
Error when running reactnativenotes, empty folders in git repository

### ISSUE THREAD

**Issue by s-x-d** [PacktPublishing/React-Native-Projects-2nd-Edition#1]
Hi,

I get errors when I run the reactnativenotes project (on android not ios). I downloaded your git repository to check/compare the code, however all the folders except the timer one are completely empty.

Any chance you can check your git repository and upload again.

Thanks,
Robin.

![reactnativenotes-error](https://user-images.githubusercontent.com/19331651/80377762-97688180-8893-11ea-852f-2c0cb89a667d.jpg)

**Comment by crs2here** [comment]
Hi did you pull from the notes branch? https://github.com/PacktPublishing/React-Native-Projects-2nd-Edition/tree/notes

**Comment by s-x-d** [comment]
Ah, no I didn't just the master. Thanks, will compare the files and try again.
